import sys
import ply.yacc as yacc
from PatitoLex import tokens

def p_PROGRAM(p):
    'PROGRAM : PROGRAM ID SEMICOLON DECLARACIONES FUNCIONES MAIN BLOQUE'

def p_DECLARACIONES(p):
    '''DECLARACIONES : VAR DECLARACIONES_1
    | empty'''

def p_DECLARACIONES_1(p):
    '''DECLARACIONES_1 : TIPO_VAR DECLARACIONES_2'''

def p_DECLARACIONES_2(p):
    '''DECLARACIONES_2 : ID DECLARACIONES_3 SEMICOLON'''

def p_DECLARACIONES_3(p):
    '''DECLARACIONES_3 : COMMA DECLARACIONES_2
    | ARRAY DECLARACIONES_3
    | empty'''

def p_ARRAY(p):
    '''ARRAY : L_SQ_BRACKET CTE_INT R_SQ_BRACKET ARRAY_2'''

def p_ARRAY_2(p):
    '''ARRAY_2 : L_SQ_BRACKET CTE_INT R_SQ_BRACKET
    | empty'''

def p_TIPO_VAR(p):
    '''TIPO_VAR : INT | FLOAT | CHAR'''

def p_FUNCIONES(p):
    '''FUNCIONES : FUNCTION TIPO_FUNC ID L_PAREN FUNCIONES_2 R_PAREN BLOQUE'''